--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jojoe77777/FormAPI
branches:
- master
projects:
  FormAPI-plugin:
    path: ""
    type: plugin
  FormAPI:
    path: ""
    type: library
    model: virion
...
